# Generated by Django 5.1.3 on 2024-11-15 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ugel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('ruc', models.CharField(max_length=11, unique=True)),
                ('str_images', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InstitucionEducativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_modular', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('ruc_ugel', models.CharField(max_length=11)),
                ('modalidad', models.CharField(choices=[('EBR', 'Educación Básica Regular'), ('EBE', 'Educación Básica Especial'), ('EBA', 'Educación Básica Alternativa'), ('CETPRO', 'Centro de Educación Técnico-Productiva')], max_length=10)),
                ('niveles', models.JSONField(default=dict)),
                ('ugel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instituciones', to='app.ugel')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('apellido_paterno', models.CharField(max_length=255)),
                ('apellido_materno', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('password', models.CharField(max_length=255)),
                ('tipo_usuario', models.CharField(choices=[('REGIONAL', 'Usuario Regional'), ('UGEL', 'Usuario UGEL'), ('DIRECTOR', 'Director')], max_length=15)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=10)),
                ('permisos', models.JSONField(default=dict)),
                ('ugel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='app.ugel')),
            ],
        ),
        migrations.CreateModel(
            name='Vacante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(max_length=50)),
                ('grado', models.CharField(max_length=50)),
                ('vacantes_regulares', models.IntegerField(default=0)),
                ('vacantes_nee', models.IntegerField(default=0)),
                ('institucion_educativa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacantes', to='app.institucioneducativa')),
            ],
        ),
    ]
