# Generated by Django 5.1.3 on 2025-02-26 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_modular', models.CharField(max_length=50)),
                ('nivel', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Ugel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('ruc', models.CharField(max_length=11, unique=True)),
                ('str_images', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VacanteFinal',
            fields=[
                ('codigo_modular', models.CharField(help_text='Código modular de la institución educativa.', max_length=10, primary_key=True, serialize=False, verbose_name='Código Modular')),
                ('nivel', models.CharField(max_length=50)),
                ('vacantes', models.TextField(default='{}', verbose_name='Vacantes Regulares')),
                ('vacantes_nee', models.TextField(default='{}', verbose_name='Vacantes NEE')),
            ],
        ),
        migrations.CreateModel(
            name='InstitucionEducativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_mod', models.CharField(max_length=10, unique=True, verbose_name='Código Modular')),
                ('cen_edu', models.CharField(default='Desconocido', max_length=255, verbose_name='Centro Educativo')),
                ('niv_mod', models.CharField(default='Desconocido', max_length=10, verbose_name='Nivel Modalidad (Código)')),
                ('d_niv_mod', models.CharField(choices=[('Inicial - Jardín', 'Inicial - Jardín'), ('Inicial - Cuna-jardín', 'Inicial - Cuna-jardín'), ('Primaria', 'Primaria'), ('Secundaria', 'Secundaria'), ('Básica Alternativa-Inicial e Intermedio', 'Básica Alternativa-Inicial e Intermedio'), ('Básica Alternativa-Avanzado', 'Básica Alternativa-Avanzado'), ('Técnico Productiva', 'Técnico Productiva'), ('Básica Especial-Primaria', 'Básica Especial-Primaria'), ('Escuela Formación Artística', 'Escuela Formación Artística'), ('Escuela Superior Pedagógica', 'Escuela Superior Pedagógica'), ('Instituto Superior Tecnológico', 'Instituto Superior Tecnológico'), ('Básica Especial', 'Básica Especial'), ('Instituto Superior Pedagógico', 'Instituto Superior Pedagógico'), ('Inicial - Programa no escolarizado', 'Inicial - Programa no escolarizado'), ('Básica Especial-Inicial', 'Básica Especial-Inicial')], default='Desconocido', max_length=50, verbose_name='Nivel Modalidad (Descripción)')),
                ('d_forma', models.CharField(default='Desconocido', max_length=50, verbose_name='Forma de Atención')),
                ('d_cod_car', models.CharField(default='Desconocido', max_length=50, verbose_name='Código de Carrera')),
                ('d_tipss', models.CharField(default='Desconocido', max_length=50, verbose_name='Tipo de Servicio')),
                ('d_gestion', models.CharField(default='Desconocido', max_length=50, verbose_name='Gestión')),
                ('d_ges_dep', models.CharField(default='Desconocido', max_length=50, verbose_name='Dependencia de Gestión')),
                ('ugel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.ugel', verbose_name='UGEL')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('dni', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('apellido_paterno', models.CharField(max_length=255)),
                ('apellido_materno', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('tipo_usuario', models.CharField(choices=[('REGIONAL', 'Usuario Regional'), ('UGEL', 'Usuario UGEL'), ('DIRECTOR', 'Director')], max_length=15)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=10)),
                ('permisos', models.JSONField(blank=True, default=dict, null=True)),
                ('codigo_modular', models.CharField(blank=True, default='SIN_CODIGO', max_length=15, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('ugel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='app.ugel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
