# Generated by Django 5.1.3 on 2025-04-23 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_institucioneducativa_niv_mod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('REGIONAL', 'Usuario Regional'), ('UGEL', 'Usuario UGEL'), ('DIRECTOR', 'Director')], default='REGIONAL', max_length=15),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='ugel',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='app.ugel'),
        ),
    ]
