# Generated by Django 5.1.3 on 2025-04-23 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_usuario_tipo_usuario_alter_usuario_ugel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='ugel',
            field=models.ForeignKey(blank=True, default='UGEL CUSCO', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='app.ugel'),
        ),
    ]
