# Generated by Django 5.1.3 on 2024-11-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_usuario_is_staff_usuario_is_superuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='codigo_modular',
            field=models.CharField(blank=True, default='SIN_CODIGO', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='permisos',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
