# Generated by Django 5.1.3 on 2024-11-29 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_usuario_codigo_modular_alter_usuario_permisos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institucioneducativa',
            old_name='codigo_modular',
            new_name='cod_ied_N',
        ),
        migrations.RemoveField(
            model_name='institucioneducativa',
            name='modalidad',
        ),
        migrations.RemoveField(
            model_name='institucioneducativa',
            name='niveles',
        ),
        migrations.RemoveField(
            model_name='institucioneducativa',
            name='ruc_ugel',
        ),
        migrations.AddField(
            model_name='institucioneducativa',
            name='cod_modular',
            field=models.CharField(default='-------', max_length=50),
        ),
        migrations.AddField(
            model_name='institucioneducativa',
            name='nivel',
            field=models.JSONField(default=list),
        ),
    ]
