# Generated by Django 5.1.3 on 2025-04-23 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_usuario_ugel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institucioneducativa',
            name='niv_mod',
            field=models.CharField(default='Desconocido', max_length=20, null=True, verbose_name='Nivel Modalidad (Código)'),
        ),
    ]
