# Generated by Django 5.1.3 on 2024-11-29 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_codigo_modular_institucioneducativa_cod_ied_n_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_modular', models.CharField(max_length=50)),
                ('nivel', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='institucioneducativa',
            name='cod_modular',
        ),
        migrations.RemoveField(
            model_name='institucioneducativa',
            name='nivel',
        ),
        migrations.AddField(
            model_name='institucioneducativa',
            name='niveles',
            field=models.ManyToManyField(related_name='instituciones', to='app.nivel'),
        ),
    ]
