# Generated by Django 5.1.3 on 2024-11-29 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_nivel_remove_institucioneducativa_cod_modular_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institucioneducativa',
            name='cod_mod',
            field=models.CharField(default='-------', max_length=50),
        ),
    ]
