# Generated by Django 5.1.3 on 2025-04-23 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_institucioneducativa_niv_mod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institucioneducativa',
            name='niv_mod',
            field=models.CharField(blank=True, default='Desconocido', max_length=20, null=True, verbose_name='Nivel Modalidad (Código)'),
        ),
    ]
