# Generated by Django 5.1.3 on 2025-04-23 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_institucioneducativa_niv_mod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institucioneducativa',
            name='d_cod_car',
            field=models.CharField(blank=True, default='Desconocido', max_length=50, null=True, verbose_name='Código de Carrera'),
        ),
        migrations.AlterField(
            model_name='institucioneducativa',
            name='d_ges_dep',
            field=models.CharField(default='Sector Educativo', max_length=50, verbose_name='Dependencia de Gestión'),
        ),
    ]
