# Generated by Django 5.1.3 on 2024-12-11 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_institucioneducativa_cod_mod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institucioneducativa',
            name='cod_ied_N',
        ),
        migrations.RemoveField(
            model_name='institucioneducativa',
            name='niveles',
        ),
        migrations.RemoveField(
            model_name='institucioneducativa',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='institucioneducativa',
            name='ugel',
        ),
        migrations.AddField(
            model_name='institucioneducativa',
            name='cen_edu',
            field=models.CharField(default='Desconocido', max_length=255, verbose_name='Centro Educativo'),
        ),
        migrations.AddField(
            model_name='institucioneducativa',
            name='d_cod_car',
            field=models.CharField(default='Desconocido', max_length=50, verbose_name='Código de Carrera'),
        ),
        migrations.AddField(
            model_name='institucioneducativa',
            name='d_forma',
            field=models.CharField(default='Desconocido', max_length=50, verbose_name='Forma de Atención'),
        ),
        migrations.AddField(
            model_name='institucioneducativa',
            name='d_ges_dep',
            field=models.CharField(default='Desconocido', max_length=50, verbose_name='Dependencia de Gestión'),
        ),
        migrations.AddField(
            model_name='institucioneducativa',
            name='d_gestion',
            field=models.CharField(default='Desconocido', max_length=50, verbose_name='Gestión'),
        ),
        migrations.AddField(
            model_name='institucioneducativa',
            name='d_niv_mod',
            field=models.CharField(choices=[('Inicial - Jardín', 'Inicial - Jardín'), ('Inicial - Cuna-jardín', 'Inicial - Cuna-jardín'), ('Primaria', 'Primaria'), ('Secundaria', 'Secundaria'), ('Básica Alternativa-Inicial e Intermedio', 'Básica Alternativa-Inicial e Intermedio'), ('Básica Alternativa-Avanzado', 'Básica Alternativa-Avanzado'), ('Técnico Productiva', 'Técnico Productiva'), ('Básica Especial-Primaria', 'Básica Especial-Primaria'), ('Escuela Formación Artística', 'Escuela Formación Artística'), ('Escuela Superior Pedagógica', 'Escuela Superior Pedagógica'), ('Instituto Superior Tecnológico', 'Instituto Superior Tecnológico'), ('Básica Especial', 'Básica Especial'), ('Instituto Superior Pedagógico', 'Instituto Superior Pedagógico'), ('Inicial - Programa no escolarizado', 'Inicial - Programa no escolarizado'), ('Básica Especial-Inicial', 'Básica Especial-Inicial')], default='Desconocido', max_length=50, verbose_name='Nivel Modalidad (Descripción)'),
        ),
        migrations.AddField(
            model_name='institucioneducativa',
            name='d_tipss',
            field=models.CharField(default='Desconocido', max_length=50, verbose_name='Tipo de Servicio'),
        ),
        migrations.AddField(
            model_name='institucioneducativa',
            name='niv_mod',
            field=models.CharField(default='Desconocido', max_length=10, verbose_name='Nivel Modalidad (Código)'),
        ),
        migrations.AlterField(
            model_name='institucioneducativa',
            name='cod_mod',
            field=models.CharField(max_length=10, unique=True, verbose_name='Código Modular'),
        ),
    ]
