# Generated by Django 5.1.3 on 2025-04-25 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_institucioneducativa_d_cod_car_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institucioneducativa',
            name='d_tipss',
            field=models.CharField(choices=[('Mixto', 'Mixto'), ('Mujeres', 'Mujeres'), ('Varones', 'Varones'), ('Desconocido', 'Desconocido')], default='Desconocido', max_length=50, verbose_name='Tipo de Servicio'),
        ),
    ]
