# Generated by Django 5.1.3 on 2024-12-11 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_institucioneducativa_cod_ied_n_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institucioneducativa',
            name='ugel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.ugel', verbose_name='UGEL'),
        ),
    ]
