# Generated by Django 5.1.3 on 2024-12-12 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_institucioneducativa_ugel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacante',
            name='institucion_educativa',
        ),
        migrations.AddField(
            model_name='vacante',
            name='codigo_modular',
            field=models.CharField(default='Desconocido', help_text='Código modular de la institución educativa.', max_length=10, verbose_name='Código Modular'),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='grado',
            field=models.CharField(max_length=20, verbose_name='Grado Educativo'),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='nivel',
            field=models.CharField(choices=[('Inicial - Jardín', 'Inicial - Jardín'), ('Inicial - Cuna-jardín', 'Inicial - Cuna-jardín'), ('Primaria', 'Primaria'), ('Secundaria', 'Secundaria'), ('Básica Alternativa-Inicial e Intermedio', 'Básica Alternativa-Inicial e Intermedio'), ('Básica Alternativa-Avanzado', 'Básica Alternativa-Avanzado'), ('Técnico Productiva', 'Técnico Productiva'), ('Básica Especial-Primaria', 'Básica Especial-Primaria'), ('Escuela Formación Artística', 'Escuela Formación Artística'), ('Escuela Superior Pedagógica', 'Escuela Superior Pedagógica'), ('Instituto Superior Tecnológico', 'Instituto Superior Tecnológico'), ('Básica Especial', 'Básica Especial'), ('Instituto Superior Pedagógico', 'Instituto Superior Pedagógico'), ('Inicial - Programa no escolarizado', 'Inicial - Programa no escolarizado'), ('Básica Especial-Inicial', 'Básica Especial-Inicial')], max_length=50, verbose_name='Nivel Educativo'),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='vacantes_nee',
            field=models.IntegerField(default=0, verbose_name='Vacantes NEE'),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='vacantes_regulares',
            field=models.IntegerField(default=0, verbose_name='Vacantes Regulares'),
        ),
    ]
