# Generated by Django 5.1.3 on 2025-04-25 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_institucioneducativa_d_tipss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institucioneducativa',
            name='d_forma',
            field=models.CharField(choices=[('Escolarizada', 'Escolarizada'), ('No aplica', 'No aplica'), ('No escolarizada', 'No escolarizada'), ('Desconocido', 'Desconocido')], default='Desconocido', max_length=50, verbose_name='Forma de Atención'),
        ),
    ]
