# Generated by Django 5.1.3 on 2024-12-12 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_vacante_institucion_educativa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacante',
            name='codigo_modular',
        ),
        migrations.AddField(
            model_name='vacante',
            name='institucion_educativa',
            field=models.ForeignKey(default='Desconocido', on_delete=django.db.models.deletion.CASCADE, related_name='vacantes', to='app.institucioneducativa'),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='grado',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='nivel',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='vacantes_nee',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='vacantes_regulares',
            field=models.IntegerField(default=0),
        ),
    ]
