# Generated by Django 5.1.3 on 2025-05-15 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_institucioneducativa_d_forma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institucioneducativa',
            name='d_gestion',
            field=models.CharField(choices=[('PÚBLICA', 'PÚBLICA'), ('PRIVADA', 'PRIVADA'), ('Desconocido', 'Desconocido')], default='Desconocido', max_length=50, verbose_name='Gestión'),
        ),
    ]
