# Generated by Django 5.1.3 on 2024-12-12 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_vacante_codigo_modular_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacante',
            name='institucion_educativa',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='vacantes', to='app.institucioneducativa'),
        ),
    ]
