# Generated by Django 5.1.3 on 2025-05-20 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_usuario_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='institucioneducativa',
            name='foto_colegio',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_colegio/'),
        ),
    ]
