# Generated by Django 5.1.3 on 2024-12-12 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_vacante_institucion_educativa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacante',
            name='institucion_educativa',
        ),
        migrations.AddField(
            model_name='vacante',
            name='codigo_modular',
            field=models.CharField(default='Desconocido', help_text='Código modular de la institución educativa.', max_length=10, verbose_name='Código Modular'),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='vacantes_nee',
            field=models.IntegerField(default=0, verbose_name='Vacantes NEE'),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='vacantes_regulares',
            field=models.IntegerField(default=0, verbose_name='Vacantes Regulares'),
        ),
    ]
